### ISSUE TITLE
`StabilityPool`: Incorrect calculation of `epochToScaleToSum`

### ISSUE THREAD

**Issue by akshaysrivastav** [Gravita-Protocol/Gravita-SmartContracts#312] opened 2023-05-05 08:29 UTC
The `StabilityPool._updateRewardSumAndProduct` does not factor in the current `P` value while calculating the new `epochToScaleToSum` value.

### Affected smart contract
- StabilityPool
https://github.com/Gravita-Protocol/Gravita-SmartContracts/blob/6f41018b0832ce6e1465fad5c0f8170f47febb3b/contracts/StabilityPool.sol#L514-L516

### Description

The current implementation of `_updateRewardSumAndProduct` function which is responsible for updating the running `SUM` and `PRODUCT` values of StabilityPool looks like this:

```solidity
	function _updateRewardSumAndProduct(
		address _asset,
		uint256 _AssetGainPerUnitStaked,
		uint256 _lossPerUnitStaked
	) internal {
		...
		uint256 currentS = epochToScaleToSum[_asset][currentEpochCached][currentScaleCached];
		uint256 newS = currentS + _AssetGainPerUnitStaked;
		epochToScaleToSum[_asset][currentEpochCached][currentScaleCached] = newS;
		emit S_Updated(_asset, newS, currentEpochCached, currentScaleCached);
                ...
        }
```

It can be seen that the current `P` value is not considered at all while calculating the `newS` value. This behaviour is incorrect and is not consistent with the design details provided at the top of `Stability.sol` file.

The correct way to calculate new `S` would be to factor in the current `P` by multiplying it to the `_AssetGainPerUnitStaked` value like this:
```solidity
		uint256 currentS = epochToScaleToSum[_asset][currentEpochCached][currentScaleCached];

		uint marginalAssetGain = _AssetGainPerUnitStaked * currentP;		// @audit
		uint newS = currentS + marginalAssetGain;

		epochToScaleToSum[_asset][currentEpochCached][currentScaleCached] = newS;
		emit S_Updated(_asset, newS, currentEpochCached, currentScaleCached);
```

Due to this bug the `SUM` i.e. `epochToScaleToSum` is calculated incorrectly.

As the entire algorithm of StabilityPool works on the concept of two crucial variables, sum S and product P, any calculation error in these two values will break the entire functionality of StabilityPool and will certainly result in loss of funds.

Hence this is a high severity bug.

#### Consider these example scenarios:

Ideal Scenario:
- Assume current values, S = 100, P = 0.5
- Liquidation occurs, assume _AssetGainPerUnitStaked = 50
- After liquidation, new S = 100 + (50 * 0.5) = 125

Current Scenario:
- Assume current values, S = 100, P = 0.5
- Liquidation occurs, assume _AssetGainPerUnitStaked = 50
- After liquidation, new S = 100 + 50 = 150

In the current implementation the `S` value incorrectly grows faster than expected.
 
### Recommendation

Consider multiplying the `_AssetGainPerUnitStaked` by current `P` value before adding it to the current `S` value. 
Actual code fix already provided above.

**Comment by 0xfornax** [comment] 2023-05-11 19:39
We appreciate the report. This is a duplicate of issue #244 (although not the exact same optics, but both suggest the same problem). Unlike Liquity/Vesta which uses single-asset Stability Pools, we have adopted some ideas from Yeti, which uses a multi-asset SP (as we do). Please note that _updateRewardSumAndProduct() is only called from offset(); offset() also calls _computeRewardsPerUnitStaked() one step before, and that is where we factor in the value of "P". It is basically the same algorithm, with a small variation in the order of things, but delivering the same final results. Albeit it ends in the same way (and therefore we cannot consider it a bug, but a design choice), we understand it might cause some confusion and will debate either re-ordering back the steps or updating the documentation.

**Closed by 0xfornax** 2023-05-11 19:39 UTC
Labels: Audit competition
