### ISSUE TITLE
Limit for maximum vessels not imposed

### ISSUE THREAD

**Issue by saxenism** [Gravita-Protocol/Gravita-SmartContracts#280] opened 2023-05-01 03:07 UTC
# Limit for maximum vessels not imposed

A malicious actor or griefer can render the `SortedVessels.insert` function useless by opening an extremely large number of vessels by spamming the `BorrowerOperations.openVessel` function an obnoxiously large number of times.

In the `SortedVessels` contract a term called `maxSize` is introduced in the `Data` struct but is never really used and the `size` parameter of a particular `Data` for an asset (`assetData`) is always incremented by 1 without checking if it is below the `maxSize` limit or not.

Here is the code snippet for reference:
```solidity
function _insert(
address _asset,
IVesselManager _vesselManager,
address _id,
uint256 _NICR,
address _prevId,
address _nextId
) internal {
Data storage assetData = data[_asset];

// List must not already contain node
require(!_contains(assetData, _id), "SortedVessels: List already contains the node");
// Node id must not be null
require(_id != address(0), "SortedVessels: Id cannot be zero");
// NICR must be non-zero
require(_NICR > 0, "SortedVessels: NICR must be positive");

address prevId = _prevId;
address nextId = _nextId;

if (!_validInsertPosition(_asset, _vesselManager, _NICR, prevId, nextId)) {
	// Sender's hint was not a valid insert position
	// Use sender's hint to find a valid insert position
	(prevId, nextId) = _findInsertPosition(_asset, _vesselManager, _NICR, prevId, nextId);
}

Node storage node = assetData.nodes[_id];
node.exists = true;

if (prevId == address(0) && nextId == address(0)) {
	// Insert as head and tail
	assetData.head = _id;
	assetData.tail = _id;
} else if (prevId == address(0)) {
	// Insert before `prevId` as the head
	node.nextId = assetData.head;
	assetData.nodes[assetData.head].prevId = _id;
	assetData.head = _id;
} else if (nextId == address(0)) {
	// Insert after `nextId` as the tail
	node.prevId = assetData.tail;
	assetData.nodes[assetData.tail].nextId = _id;
	assetData.tail = _id;
} else {
	// Insert at insert position between `prevId` and `nextId`
	node.nextId = nextId;
	node.prevId = prevId;
	assetData.nodes[prevId].nextId = _id;
	assetData.nodes[nextId].prevId = _id;
}

assetData.size = assetData.size + 1;
emit NodeAdded(_asset, _id, _NICR);
}
```

This is not a critical issue. However, a motivated attacker/griefer could definitely go down this route to tamper with the functioning of the Gravita protocol.

## Recommended Mitigation Steps

1. Impose the `maxSize` restriction in the `SortedVessels.sol` contract.
2. Impose a limit on the number of vessels a particular address can open up and also you could limit the creation rate of new vessels.\n

**Comment by 0xfornax** [comment] 2023-05-01 20:05
We appreciate the report. Duplicate of https://github.com/Gravita-Protocol/Gravita-SmartContracts/issues/223.

**Closed by 0xfornax** 2023-05-01 20:05 UTC
Labels: Audit competition
