### ISSUE TITLE
`FeeCollector.collectFees` reverts due to infinite loop

### ISSUE THREAD

**Issue by akshaysrivastav** [Gravita-Protocol/Gravita-SmartContracts#269] opened 2023-04-29 08:01 UTC
`FeeCollector.collectFees` does not increment the `for` loop's index `i` when the `expiredAmount` is `0` and `continue` statement is executed. This results in an infinite loop which reverts due to block gas limit.

### Affected smart contract

- FeeCollector
https://github.com/Gravita-Protocol/Gravita-SmartContracts/blob/5e45123d169a126a3055945373421e1bda5515b9/contracts/FeeCollector.sol#L160-L163

### Description

This is how the `collectFees` function looks like:
```solidity
	function collectFees(address[] calldata _borrowers, address[] calldata _assets) external override {
		...
		for (uint256 i = 0; i < borrowersLength; ) {
			...
			uint256 expiredAmount = _calcExpiredAmount(sRecord.from, sRecord.to, sRecord.amount);
			if (expiredAmount == 0) {
				continue;
			}
			...
			unchecked {
				i++;
			}
		}
	}
```

It can be seen that to save some gas the `for` loop's index is updated at the end in an `unchecked` block. However in between the loop's implementation there exist a `continue` statement which gets executed when `expiredAmount` is `0`. But in that specific case the index of loop in not incremented. So the loop's execution continues with the same index `i` value resulting in an infinite loop which at last reverts due to transaction (or block) gas limit.

Due to this bug the `collectFees` function becomes unusable when the `expiredAmount` for any of the `borrower-asset` pair is zero. Hence bug results in DoS in all scenarios when `expiredAmount` of any user is `0`.

### Attack scenario

New test file was created and ran using `yarn test path-to-file`.

```javascript
const { expect } = require("chai");
const { BigNumber } = require("ethers");
const { ethers } = require("hardhat");
const {
    time,
} = require("@nomicfoundation/hardhat-network-helpers")

const { parseUnits, parseEther, formatUnits, formatEther } = ethers.utils

describe("FeeCollectorAudit", async () => {
    let feeCollector, debtToken, assetToken, admin, user, treasury;

    const MIN_FEE_SECONDS = 7 * 86400;
    const FEE_EXPIRATION_SECONDS = 175 * 86400;
    const MIN_FEE_FRACTION = parseEther('0.038461538')

    beforeEach(async () => {
        [admin, user, treasury] = await ethers.getSigners()

        const ERC20MockFactory = await hre.ethers.getContractFactory("ERC20Mock");
        debtToken = await ERC20MockFactory.deploy("Debt Mock", "DDD", 18);
        assetToken = await ERC20MockFactory.deploy("Asset Moch", "AAA", 18);

        const FeeCollectorFactory = await hre.ethers.getContractFactory("FeeCollector");
        feeCollector = await FeeCollectorFactory.deploy();
        await feeCollector.setAddresses(
            admin.address,
            admin.address,
            ethers.constants.AddressZero,
            debtToken.address,
            treasury.address,
            false
        )
    })

    const getCurrentBlockTS = async () => (await ethers.provider.getBlock(await ethers.provider.getBlockNumber())).timestamp;
    const bn = (num) => BigNumber.from(num)

    const calcFeeAndAmount = (debtAmount) => {
        const fee = bn(debtAmount).mul(MIN_FEE_FRACTION).div(parseEther('1'))
        const amount = bn(debtAmount).sub(fee);
        return [fee, amount]
    }

    it("Bug: collect: index not updated", async () => {
        const depositAmount = parseEther('1000')
        await debtToken.mint(feeCollector.address, depositAmount)
        await feeCollector.increaseDebt(user.address, assetToken.address, depositAmount)

        await expect(feeCollector.collectFees([user.address], [assetToken.address])).to.be.reverted

    })
})
```
To further validate the issue, I added some `console.log`s just before the `continue` statement in the smart contract.

This was the console output:
```
...
expiredAmount 0
loop index 0
expiredAmount 0
loop index 0
expiredAmount 0
loop index 0
expiredAmount 0
loop index 0
expiredAmount 0
loop index 0
expiredAmount 0
loop index 0
...
```

### Recommendation

Consider changing the `for` loop's implementation to a non-optimised one like:
```solidity
for (uint i; i < borrowersLength; i++) {}
```
Or manually increment the index before the `continue` statement
```solidity
if (expiredAmount == 0) {
        i++;
	continue;
}
```

**Comment by 0xfornax** [comment] 2023-05-01 20:07
Thanks for the report! Duplicate of https://github.com/Gravita-Protocol/Gravita-SmartContracts/issues/222

**Closed by 0xfornax** 2023-05-01 20:07 UTC
Labels: Audit competition
