### ISSUE TITLE
Missing checks for zero address

### ISSUE THREAD

**Issue by Phantasmagoria13** [Gravita-Protocol/Gravita-SmartContracts#210] opened 2023-04-24 18:17 UTC
### Severity
Low

### Title

Missing checks for zero address

### Affected smart contract
GRVTStaking.sol

https://github.com/Gravita-Protocol/Gravita-SmartContracts/blob/d3ff41a4cb8d970c68a9ae8732ddebb6dfa54b21/contracts/GRVT/GRVTStaking.sol#L167

### Description
Checking addresses against zero-address during initialization or during setting is a security best-practice. However, such checks are missing in address variable initializations/changes in many places.

Allowing zero-addresses will lead to contract reverts and force redeployments if there are no setters for such address variables.

### Recommendation
Check that address is not zero

**Comment by 0xfornax** [comment] 2023-05-11 14:11
We appreciate the submission but the rules are clear that critiques of best practices would not be eligible. Duplicate of #208

**Closed by 0xfornax** 2023-05-11 14:11 UTC
Labels: Audit competition
