### ISSUE TITLE
Initializers could be front-run

### ISSUE THREAD

**Issue by Phantasmagoria13** [Gravita-Protocol/Gravita-SmartContracts#209] opened 2023-04-24 18:17 UTC
### Severity
Low

### Title

Initializers could be front-run

### Affected smart contract
*Instances (27)*:
```solidity
File: ActivePool.sol

87: 	) external initializer {

88: 		__Ownable_init();

89: 		__ReentrancyGuard_init();

```

```solidity
File: BorrowerOperations.sol

99: 	) external initializer {

100: 		__Ownable_init();

```

```solidity
File: CollSurplusPool.sol

33: 	) external initializer {

34: 		__Ownable_init();

```

```solidity
File: DefaultPool.sol

31: 	function setAddresses(address _vesselManagerAddress, address _activePoolAddress) external initializer {

32: 		__Ownable_init();

```

```solidity
File: FeeCollector.sol

45: 	) external initializer {

47: 		__Ownable_init();

```

```solidity
File: GRVT/CommunityIssuance.sol

51: 	) external initializer {

52: 		__Ownable_init();

```

```solidity
File: GRVT/GRVTStaking.sol

56: 	) external initializer {

59: 		__Pausable_init();

60: 		__ReentrancyGuard_init();

61: 		__Ownable_init();

```

```solidity
File: GRVT/LockedGRVT.sol

37: 	function setAddresses(address _grvtAddress) public initializer onlyOwner {

```

```solidity
File: PriceFeed.sol

50: 	) external initializer {

51: 		__Ownable_init();

```

```solidity
File: SortedVessels.sol

72: 	function setAddresses(address _vesselManagerAddress, address _borrowerOperationsAddress) external initializer {

73: 		__Ownable_init();

```

```solidity
File: StabilityPool.sol

237: 	) external initializer {

238: 		__ReentrancyGuard_init();

```

```solidity
File: VesselManager.sol

130: 	) external initializer {

```

```solidity
File: VesselManagerOperations.sol

64: 	) external initializer {

65: 		__Ownable_init();

```

### Description
There is nothing preventing another account from calling the initializer before the contract owner. In the best case, the owner is forced to waste
gas and re-deploy. In the worst case, the owner does not notice that his/her call reverts, and everyone starts using a contract under the control of an attacker

### Recommendation
Add a control that makes initialize() only call the Deployer Contract or EOA;

```solidity
if (msg.sender != DEPLOYER_ADDRESS) {
            revert NotDeployer();
}
```

**Comment by 0xfornax** [comment] 2023-05-13 14:00
We appreciate the submission. Duplicate of https://github.com/Gravita-Protocol/Gravita-SmartContracts/issues/203

**Closed by 0xfornax** 2023-05-13 14:00 UTC
Labels: Audit competition
