### ISSUE TITLE
Timelock is unable to receive ETH

### ISSUE THREAD

**Issue by akshaysrivastav** [Gravita-Protocol/Gravita-SmartContracts#232] opened 2023-04-26 09:03 UTC
The Timelock does not contain a `receive` or `payable fallback` function

### Affected smart contract

- Timelock

https://github.com/Gravita-Protocol/Gravita-SmartContracts/blob/5e45123d169a126a3055945373421e1bda5515b9/contracts/Timelock.sol#L77

### Description

The above code snippet shows that the `fallback` function was commented out in the `Timelock` smart contract. The contract does not contain a `receive` function either. Due to this the `Timelock` contract is unable to receive any ETH.

Receiving ETH is a crucial feature all governance/admin modules (like timelock contracts) as these privileged contracts are responsible for collecting funds (like protocol fee, operational funds, etc) from other protocol contracts and EOAs. These funds are then managed (withdrawn or transferred) appropriately by the governing bodies.

As the Timelock contract is not upgradable, it can never have the ability to receive and hold plain ETH which might appear as a future need for Gravitas protocol.

### Attack scenario

This PoC was created in new test file with content as:
```javascript
const { ethers } = require("hardhat");
const Timelock = artifacts.require("Timelock")

contract("Timelock", async () => {

    it("Cannot receive ETH", async () => {
        const timelock = await Timelock.new(3 * 86400)
        const admin = await ethers.getSigner()
        expect(await timelock.admin()).to.eq(admin.address)

        let tx = {
            to: timelock.address,
            value: '100'
        }

        try {
            await admin.sendTransaction(tx)
        } catch (err) {
            assert.include(err.message, "revert")
        }
    })
})
```

### Recommendation
Consider adding a `receive` function in the Timelock contract. This maintains the future compatibility of Timelock without impacting any current functionality.

```solidity
        receive() external payable {}
```

**Comment by 0xfornax** [comment] 2023-05-11 14:35
Thanks for the report! Duplicate of https://github.com/Gravita-Protocol/Gravita-SmartContracts/issues/207

**Closed by 0xfornax** 2023-05-11 14:35 UTC
Labels: Audit competition
