### ISSUE TITLE
PriceFeed: Uneven price deviation threshold

### ISSUE THREAD

**Issue by akshaysrivastav** [Gravita-Protocol/Gravita-SmartContracts#240] opened 2023-04-27 07:35 UTC
The `PriceFeed._isPriceChangeAboveMaxDeviation` allows uneven max price deviations in cases of price increasing and decreasing.

### Affected smart contract
- PriceFeed
https://github.com/Gravita-Protocol/Gravita-SmartContracts/blob/5e45123d169a126a3055945373421e1bda5515b9/contracts/PriceFeed.sol#L193-L203

### Description

For a single `OracleRecord.maxDeviationBetweenRounds` value the `_isPriceChangeAboveMaxDeviation` function allows different price deviation limits in the cases where price is increasing versus when price is decreasing.

Consider this scenario:
- Price of a token in previous round was 1000e18.
- `maxDeviationBetweenRounds` is set to 0.5e18.
- When price is increasing
    - The ideal limit should be 1500e18
    - But the actual calculated limit comes out to be 2000e18
- When price is decreasing
    - The ideal limit should be 500e18
    - The actual calculated limit also comes out to be 500e18

Hence it can be seen that when max deviation is set as 50%, the actual limit while the price decreases comes out to be 50% of previous price but when the price increases the actual limit comes out to be 100% of the previous price.

This creates uneven price deviation exposure for users, users are exposed to deviation in one direction (price increase) more than the other direction (price decrease).

This uneven exposure can create unexpected issues in sudden market movement. A short spike in price can be misused by attacker to borrow funds from protocol as the price spike incorrectly falls under the deviation limit. 

### Recommendation

Consider using two deviation limit parameters each of which will be used separately for price increase and price decrease scenario.

**Comment by 0xfornax** [comment] 2023-05-11 14:48
Thanks for the report! Duplicate of [https://github.com/Gravita-Protocol/Gravita-SmartContracts/issues/236](https://github.com/Gravita-Protocol/Gravita-SmartContracts/issues/207)

**Closed by 0xfornax** 2023-05-11 14:48 UTC
Labels: Audit competition
